/* Auto-generated by toki_git_commit — commit stamp for Show Version */
window.TOKI_BUILD = {
  "hash": "6c2bf0a",
  "hashFull": "6c2bf0a3fb16fb6099719a552994c399a957068c",
  "date": "2026-08-13 14:30:13 -0400",
  "subject": "Added Source Switching Support",
  "source": "git"
};
