/* Auto-generated by toki_git_commit — commit stamp for Show Version */
window.TOKI_BUILD = {
  "hash": "b56c092",
  "hashFull": "b56c0920cf3e26b3c632ff79aff608d48b45f49f",
  "date": "2026-08-12 23:07:15 -0400",
  "subject": "Fixed Multi-View",
  "source": "git"
};
