/* Auto-generated by toki_git_commit — commit stamp for Show Version */
window.TOKI_BUILD = {
  "hash": "7c5cdaf",
  "hashFull": "7c5cdaf844b04cc956513b9416d9cd13a608514c",
  "date": "2026-08-13 13:40:57 -0400",
  "subject": "Full Refactor running off of GSHEET API",
  "source": "git"
};
